# frozen_string_literal: true

source "https://rubygems.org"

ruby '2.4.1'

gem 'rspec'
gem 'rubocop'
gem 'simplecov', require: false, group: :test
gem 'simplecov-console', require: false, group: :test
